version: '3.3'

services:
  web:
    image: node:18.20.2
    restart: always
    working_dir: /home/app
    ports:
      - 80:3000
    volumes:
      - .:/home/app
    command: "bash -c 'npm install && npm start'"

  db:
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: asdf535opij!
    ports:
      - 9856:3306
    volumes:
      - ./db:/var/lib/mysql
    
